name: Build Qwak Model on PR

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
        - 'main'                                            # replace with your `main` or `master` branch
    paths-ignore:
        - "*.md"
  workflow_dispatch:  # Enables manual trigger

jobs:
  build-model:
    runs-on: self-hosted        # change with your requirede instance for example [ubuntu-latest]

    steps:

    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Generate dynamic branch name (manual runs only)
      if: github.event_name == 'workflow_dispatch'
      run: |                                                # Triggered manually via dispatch
        branch_name="manual-${{ github.actor }}"
        echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV

    - name: Extract branch name (automatic runs)
      if: github.event_name != 'workflow_dispatch'          
      run: |                                                # Triggered on pull request
        branch_name="${GITHUB_REF#refs/heads/}"
        echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV

    - name: Build Qwak Model
      id: qwak-build
      uses: qwak-ai/build-action@main
      with:
        qwak-api-key: ${{ secrets.QWAK_API_KEY }}
        model-id: ${{ vars.QWAK_MODEL_ID }}                                     # stored as a Repository variable
        instance: 'medium'                                                      # replace with the required instance
        tags: '${{ github.event.pull_request.title }},${{ github.head_ref }}'   # tag the build with the branch name
        # other config inputs as needed

    - name: Create build_metadata.json
      run: |
        echo '{
            "build_id": "${{ env.build-id }}",
            "build_status": "${{ env.build-status }}",
            "build_metrics": "${{ env.build-metrics }}"
        }' > build_metadata.json

    - name: Upload build_metadata.json as artifact
      uses: actions/upload-artifact@v3
      with:
        name: build_metadata                                # The name under which the artifact will be stored and can be downloaded later
        path: build_metadata.json                           # The actual file you are uploadin
        retention-days: 1