name: Deploy Successful Qwak Model Build

on:
  workflow_dispatch:  # Removed pull_request trigger and kept only manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest  # Removed the if condition
    steps:

      # Optional: Additional step to undeploy a test or shadow deployment
      
      - name: Deploy the latest successful Qwak Model Build with the Git branch tag
        uses: qwak-ai/deploy-action@main
        with:
          qwak-api-key: ${{ secrets.QWAK_API_KEY }}
          deploy-type: 'batch'  # Replace with the deployment type you need
          model-id: ${{ vars.QWAK_MODEL_ID }}  # Using the repository variable for model ID
          instance: 'small'  # Optional, specify if you want a different instance type