name: Deploy Successful Qwak Model Build To Test

on:
  workflow_run:
    workflows: ["Build Qwak Model on PR"]
    types:
      - completed

  workflow_dispatch:  # Enables manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    # Download the build_metadata.json artifact from the previous workflow
    - name: Download build_metadata artifact
      uses: actions/download-artifact@v3
      with:
        name: build_metadata
        path: ./  # Downloads to the current working directory

    # Install jq for JSON parsing
    - name: Install jq
      run: sudo apt-get install jq

    # Parse build_metadata.json to get build-id and other metrics
    - name: Parse build_metadata.json
      run: |
        build_id=$(jq -r '.build_id' build_metadata.json)
        build_status=$(jq -r '.build_status' build_metadata.json)
        build_metrics=$(jq -r '.build_metrics' build_metadata.json)
        echo "build_id=$build_id" >> $GITHUB_ENV
        echo "build_status=$build_status" >> $GITHUB_ENV
        echo "build_metrics=$build_metrics" >> $GITHUB_ENV
    

    # Install yq for YAML manipulation
    - name: Install yq
      run: sudo apt-get install -y jq yq


    # Generate the YAML config file for variations
    - name: Generate YAML config
      run: |
          yq eval '{
            "realtime": {
              "variation_name": "shadow-gha",
              "audiences": [
                {
                  "id": "audience_id",
                  "routes": [
                    {
                      "variation_name": "default",
                      "weight": 100,
                      "shadow": false
                    },
                    {
                      "variation_name": "shadow-gha",
                      "weight": 20,
                      "shadow": true
                    }
                  ]
                }
              ],
              "fallback_variation": "shadow-gha"
            }
          }' > config.yaml
  

    # Deploy model to a shadow/canary endpoint  
    - name: Deploy Qwak Build
      uses: qwak-ai/deploy-action@v1  # Replace with the actual repo and version
      with:
          deploy-type: 'realtime'                           # Replace with the deployment type you need
          model-id: ${{ vars.QWAK_MODEL_ID }}               # Using the repository variable for model ID
          build-id: ${{ env.build_id }}                     # Using the environment variable set earlier
          param-list: |                                     # Add the parameters according to your deployment type
            'variation-name=shadow-gha,
            from-file=config.yaml'
          instance: 'small'                                 # Optional, specify if you want a different instance type
          replicas: 1                                       # Optional, specify if you want more replicas
          environment: 'prod'                               # Optional, specify if you want a different environment
          timeout-after: 30                                 # Optional, specify if you want a different timeout


    